/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type RoomAction =
  | {
      action: "join";
    }
  | {
      action: "leave";
    }
  | {
      action: "chat";
      payload: {
        message: "string";
      };
    }
  | {
      action: "mark";
      payload: {
        index: "number";
      };
    }
  | {
      action: "unmark";
      payload: {
        index: "number";
      };
    };
