/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An outgoing client websocket message sent when a client performs an action in a room
 */
export type RoomAction = (
  | {
      action: "join";
      payload?: {
        nickname: string;
      };
    }
  | {
      action: "leave";
    }
  | {
      action: "chat";
      payload: {
        message: string;
      };
    }
  | {
      action: "mark";
      payload: {
        row: number;
        col: number;
      };
    }
  | {
      action: "unmark";
      payload: {
        row: number;
        col: number;
      };
    }
  | {
      action: "changeColor";
      payload: {
        color: string;
      };
    }
) & {
  /**
   * JWT for the room obtained from the server
   */
  authToken: string;
};
